name: flutter_awesome_ui
description: Package to make easier the proccess of creating a awesome ui
version: 1.3.0
homepage: https://github.com/ziqq/flutter_awesome_ui

publish_to: 'none'

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

