name: flutter_awesome_ui
description: Package to make easier the proccess of creating a text form field. The component created is fully customizable to your needs.
version: 1.0.0
homepage: https://github.com/ziqq/awesome_input

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

